---
name: Build & Publish Docker Image

# Only builds the image if a release was created.
# This guarantees the commit is tagged and on main branch.
# (see https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)

# yamllint disable-line rule:truthy
on: release

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/docker.yml@a28fa2f991164959262587011188af99a7f0cb20
    secrets: inherit
