---
name: Build & Publish Docker Image

# Only builds the image if a release was created.
# This guarantees the commit is tagged and on main branch.
# (see https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)

# yamllint disable-line rule:truthy
on: release

jobs:
  default:
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_docker_callable.yml@04725cdbd18417c3be81e83984ea0baacd3d836f
    secrets: inherit
    with:
      image-name: "fluent-bit-multiline"
      upload-security-scan-results: true
      push: true
