---
name: Build & Push Docker Image

# Only builds the image if a release was created.
# This guarantees the commit is tagged and on main branch.
# (see https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)

# yamllint disable-line rule:truthy
on: release

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/docker_dockerhub_release_callable.yml@c2e27d976e1221942c2186e512183ab79c1c8bac # 1.15.4
    secrets: inherit
    with:
      image-name: "fluent-bit-multiline"
      upload-security-scan-results: true
      push: true
