---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_linter_callable.yml@04725cdbd18417c3be81e83984ea0baacd3d836f
    secrets: inherit
