---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@e58bc055e14da4c9636b1b39357f89fcd512b27a
    secrets: inherit
