---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_spelling_callable.yml@e87de55f19cc1e069426c42120094e7e2446dad4
    secrets: inherit
